<template>
	<MakeProblem listEndLabel="b" :listItemScoreTexts="['(5%)','(5%)']">
		<template #problem>
			Let $G=(V,T,S,P)$ be the phrase‑structure grammar with $V=\{0,1,A,S\}$, $T=\{0,1\}$,
			and the set of productions $P$ consisting of $S\to1S$, $S\to10A$, $A\to0A$, and $A\to0$.
		</template>
		<template #a>Show that $1111000$ belongs to the language generated by $G$.</template>
		<template #b>What is the language generated by $G$?</template>
	</MakeProblem>
</template>
